Q1:"Intervistatore:Secondo lei vi sono delle criticità rispetto all'utilizzo dello score NEWS2? Se sì, quali? Può parlarmene?"
Q2:"Intervistatore:Vi sono delle difficoltà o delle problematiche nell'applicazione del protocollo sepsi in autonomia in seguito ad un punteggio positivo dello score NEWS2? Relativamente alle criticità e/o difficoltà esplicitate, mi può raccontare un episodio concreto."
Q3:"Intervistatore:Quali sono le motivazioni che possono portare all'interruzione dell'applicazione del protocollo sepsi nonostante il punteggio positivo dello score NEWS2?"
Q4:"Intervistatore:Quali sono le sfide che gli infermieri devono affrontare nel rivolgersi al medico per il proseguo del protocollo sepsi? C'è collaborazione tra le due figure professionali nell'applicazione del protocollo?" 
Q5:"Intervistatore:Quali sono secondo lei le competenze necessarie per applicare in autonomia il protocollo sepsi nel setting di emergenza-urgenza?"
Q6:"Intervistatore:Secondo lei ha ricevuto un'adeguata formazione rispetto alla gestione di un paziente con sepsi o shock settico? Secondo lei è necessaria un'ulteriore formazione in questo campo?"
Q7:"Intervistatore:L'utilizzo dello score NEWS2 secondo lei ha un impatto positivo nella pratica clinica quotidiana? In quale modo l'utilizzo dello score NEWS2 ha influito sulla cura, l'efficacia e la sicurezza dei pazienti?"
Q8:"Intervistatore:C'è qualcos'altro che vorrebbe aggiungere/condividere prima di concludere l'intervista?"
